### ISSUE TITLE
Accuracy differences in results between WNTRSimulator and EpanetSimulator

### ISSUE THREAD

**Issue by fabosilva** [USEPA/WNTR#134]
I have already tested several network's examples and, comparing the results obtained using wntrsimulator and epanetsimulator, I could notice that there are differences from the second decimal place between the two methods. Is there some way to adjust or fix the calculation of the accuracy using wntrsimulator? I've mainly observed pressure's results.

**Comment by 1-1-2** [comment]
我也观察到了类似的情况。
我认为这个问题主要的原因是，两个内核对于方程组的实现方式和方程组的求解器是不一样的。在满足残差值的情况下面，结果会有稍微的偏差。这个相对误差量级大概在十的负四次方。
我个人认为，因为都是基于迭代的求解，所以这种误差应该是没有办法完全消除的。

**Comment by kaklise** [comment]
The comment above has been translated here "I have observed a similar situation.
I think the main reason for this problem is that the two kernels implement the equations differently than the equation solvers. Under the condition of satisfying the residual value, the result will have a slight deviation. This relative error level is probably in the negative fourth power of ten.
I personally think that because it is based on iterative solutions, this error should not be completely eliminated."

**Comment by kaklise** [comment]
The two simulators will have slight differences in their results.  WNTR includes several tests to compare results from the EpanetSimulator and the WNTRSimulator.  The threshold for acceptable absolute deviation is 1e-3 to 1e-5 (depending on the variable), we use a relative error of 1e-3, though it is often quite smaller.  

When using the EpanetSimulator, you can set wn.options.solver.accuracy.  This could resolve the issue you are seeing in the second decimal place.  This option is not used by the WNTRSimulator (see https://wntr.readthedocs.io/en/latest/framework.html#limitations)
