### ISSUE TITLE
base_value must be a number

### ISSUE THREAD

**Issue by balks** [USEPA/WNTR#145]
I'm trying to set the base_head on a reservoir to the average value from a simulation. Turns out that a numpy.float32 (from the results.mean() ) is not accepted by the @base_head.setter, so I have to convert to float first. 

r.base_head = res.node['head'][rid].mean() --> ValueError: TimeSeries->base_value must be a number
Error in wntr\network\elements.py", line 1221, in base_value 

wntr.__version__ =  '0.2.2'

Workaround: 
r.base_head = float(res.node['head'][rid].mean())  --> no error

This should be no error, I'd say. Maybe wrapping base_value in float() will do, but it's probably not the best solution.
I think this applies to other setters as well. At least I have a similar issue with add_demand.

**Comment by dbhart** [comment]
@balks – thank you; I agree this should not be an error, though many packages have problems with numpy dtypes not being recognized as numbers…

**Comment by kaklise** [comment]
I believe this issue has been resolved, perhaps because of updates to Pandas.  In the example below (based on the water network and simulation results in the getting started example) the value returned by mean is a float and there is no error.   If we run into this issue again, we could take care of numpy dtypes in the setter functions that are now used for network attributes.

```
res = wn.get_node('River')
res.base_head = results.node['head']['River'].mean()
print(res.base_head)
```
