### ISSUE TITLE
EPANET 2.2 Unbalanced hydraulics results

### ISSUE THREAD

**Issue by dionikolop** [USEPA/WNTR#175]
Hi,
I am running a parallel bunch of simulations with different quality parameters using the multiprocessing library. I use the EPANET 2.2 solver with the PDA option. In some simulations (randomly) I get strange results, which are the outcome of unbalanced hydraulic simulation. I did some tests with the EPANET GUI and confirmed it. Is there an option to check via WNTR if the results of a PDA simulation are unbalanced when it finishes? I know that I can parse the .rpt file generated but it is a hassle. 
Thanks!

**Comment by kaklise** [comment]
Since you were able to replicate the issue in the EPANET GUI, I suggest you open an issue on that site as well.  WNTR currently does not include functions to parse the EPANET report file, but that has been suggested (#46).    If you'd like to contribute that functionality, please let us know.  Otherwise, we'll keep this in mind as we're adding new features.

**Comment by kaklise** [comment]
I'm going to close this issue and keep #46 open for the report file feature request.
