### ISSUE TITLE
Simulation did not converge. Jacobian is singular at iteration 0

### ISSUE THREAD

**Issue by Mottabata** [USEPA/WNTR#187]
Hi,

I have been switching to do simulation using WNTR. I went through your very helpful examples and learnt so much. I have a problem that i can't get my head around. every time i use a different network other than those in the examples I keep receiving the same error "Simulation did not converge. Jacobian is singular at iteration 0". I read your previous thread on this and how nominal and minimum pressure can fix it but I don't know where such values could be switched?

![image](https://user-images.githubusercontent.com/77415566/107677604-73cac800-6c68-11eb-8717-f9b6b5e176f3.png)

**Comment by kaklise** [comment]
This can be caused by several factors, including the initial conditions of the system.  Are you able to run a simulation without pipe leaks?  I'm happy to take a look at the model/example if you are able to share it.  You can email the files to me at kaklise@sandia.gov

**Comment by Mottabata** [comment]
Hi Klise,

What initial conditions might have affected it? I was able to run a simulation in EPANET with no issues.

Thanks for your time and help,
MB

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kaklise** [comment]
The issue here is that the WNTRSimulator is not able to determine pressure at isolated nodes.  Currently, the WNTRSimulator identifies isolated nodes by checking to see if nodes are connected to a source (tank or reservoir).  This needs to be extended to identify nodes that become isolated when an active valve is connected to an upstream closed link (for PRVs) or downstream closed link (for PSVs).  We are working on software patch to resolve the issue.  

In the example listed above, the active valve that caused this issue was identified by running the EpanetSimulator (or EPANET) with a full status report.

**Comment by kaklise** [comment]
Updates in #206 resolve this issue.  This includes a condition that checks for upstream and downstream sources for PRVs, PSVs, and FCVs.  We will tag these updates in a release soon.
