### ISSUE TITLE
Cybersecurity - Simulating an attack on actuators/sensors values

### ISSUE THREAD

**Issue by theh2oweb** [USEPA/WNTR#227]
Hi,

I'm working on a cybersecurity project related to water distribution systems.
The idea is to be able to configure some kind of attacks (sensor reporting forged value, actuator doing forged action, ...)
The attack results should show the impact in the hydraulic results : Tank value going empty but still reporting full.

I tried looping a step by step WNTR simulation without luck so far.
My idea is :
1 - Remove controls
2 - Loop between start_time and duration using timestep
2.1 - If timestep in attack_timerange
2.1.1 - Apply sensor attack (for example, setting tank's head at max_level like if it was full)
2.2 - Add controls back into wn for related actions to apply (reading full value of tank sensor therefore closing approvisionning pumps)
2.3 - Remove controls (to avoid simulation to re-apply control's actions)
2.4 - Run simulation
2.5 - Save results
2.6 - Loop to 2.1 until timestep = duration...
3 - Plot combined results

My issue is with step 2.1.1 (or maybe more :-)) where I can't seem to be able to change/attack the tank's sensor reported value.
I understand WNTR may not be made for such behavior and tank sensor's head value seems read-only.
Still the tank's attributes (like pressure/level/head) are updated at each simulation round but I did not find a way to manually update them to simulate the attack.
I've looked at the code, even though I'm not so fluent with python, and found some _node_reg but still no luck exploiting it.

Do you have any idea/advice to if it's possible ? If yes, how to simulate such an attack using WNTR ?

Thanks for any response and time you will spend answering.

Regards.

**Comment by ucchejbb** [comment]
So, I don't think you should be changing the results structure (tank level (in this example)). You COULD do this by just resetting the simulation to conditions at that timepoint with a new tank level. This effectively restarts the simulation. BUT, as you point out from a cyber perspective you are really changing how the system responds to wrong data. So, the tank's level really isn't changed, the system/controls just thinks it changes. So because you want to modify how the system will respond at that moment if it thinks the tank is full. So, if the normal control scheme would be to begin draining the tank, then you should implement such a control action. If the false information were "permanent" then the system just continues to think the tank is full until it is actually drained. (So that is the modeled behavior you want to see). If the false signal somehow changes to replicate a draining activity, but much slower than reality, then that would have to be modeled (simulated) outside of the EPANET/WNTR hydraulic simulator. 

Shorter version, You need to simulate/modify responses based on the expected false information BUT with the real system hydraulic information. You will need to maintain/simulate a false data stream outside WTNR that is then used to control response.

So
1. Analyze current controls/rules for elements that could be related to attacked data
2. Create data structure to store real/false data
---You can populate this from results, but also add in false data prior to step 3.
3. Use this new data structure to create appropriate control actions -- It is probably easier to control these yourself with or without an attack for those possible key components. (your 2.2)

The simulation of the system MUST be using the actual results at any given moment based on the starting conditions and control actions, but you are applying a false mask to alter when actions are occurring throughout that simulation. In the simplest case you can just add a control that says "turn pump off at time 100" to simulate false data being provided at time 100 (and stop other associated controls/rules). This isn't as dynamic, but could be a good test case for what a simulation would look like. 

Hope that helps.

**Comment by theh2oweb** [comment]
Hi @ucchejbb !

You're right, I shouldn't be changing the results (levels/heads) of the simulation, just how the controls behave to not interfere with the real values.
I guess, I have to work on the controls then. I'll get back at it and let you know what I can reach.

Thank you for your answer.
Cheers

**Comment by dbhart** [comment]
Hi @theh2oweb,

If you want to look at my fork (https://github.com/dbhart/WNTR) I have a “cyber” branch that I believe will provide the functionality you are looking for. There are two files, wntr/sim/realtime.py and wntr/tests/test_sim_realtime.py that have the classes and an example (in the test file) on how to use this. This is functionality that will go into the main WNTR release, probably next release.

I also recommend https://github.com/afmurillo/DHALSIM from @afmurillo as a place where someone has used WNTR in this way.

@afmurillo, I also believe that this same branch will address some of the issues you were running into with WNTR and trying to use the EPANET simulator with the internal setlinkproperty() function exposed within the loop.

Thanks,

dbhart

**Comment by dbhart** [comment]
Appologies, the correct branch name in my fork is "realtime"

**Comment by theh2oweb** [comment]
Hi @dbhart !
I'll have a look at all your suggestions.
Thank you for your time.
Regards

**Comment by afmurillo** [comment]
Hello @dbhart thank you very much for suggesting DHALSIM! I'm excited to see the new functionality of WNTR from your branch, all the best! 
Hello @theh2oweb I think DHALSIM offers the functionality that you are looking for. Any doubts or issues you have with DHALSIM, just let me know and I will be more than happy to help.

**Comment by theh2oweb** [comment]
Hi @afmurillo,

Dhalsim is next on the list. Will try to play with it during this week. Thanks for your help.

@dbhart , I was able to run the test_sim_realtime but I didn't understand how to make the realtime class do what I need for the moment. But still thank you. I'll see if I don't find something easier for me.

Have a nice day guys !

**Comment by dbhart** [comment]
@afmurillo just as an FYI, I was able to modify the new EPANET realtime simulator to now be able to provide quality output at a sensor output using simultaneous hydraulic/water quality execution. I'm going to add a sensor using quality to the test file (example) in my fork/branch.

**Comment by theh2oweb** [comment]
Hi @afmurillo !

I've used [Dhalsim](https://github.com/afmurillo/DHALSIM) successfully and obtained the closest results to what is expected.
I'll be exploring a little bit more and maybe will send you questions to ask for some details.

Thank you everyone !
