### ISSUE TITLE
Running EPANET simulation on Mac with ARM M1 processor

### ISSUE THREAD

**Issue by tyjchenXyl** [USEPA/WNTR#321]
I have WNTR version 0.6.0.dev0 installed on my machine running python 3.9.15, and tried to run the following steps to open/execute an INP file
```
import wntr as wn
m = wn.network.WaterNetworkModel('model.inp')
m.options.hydraulic.demand_model = 'DDA'
sim = wn.sim.EpanetSimulator(m)
results = sim.run_sim()
```
Getting back the error message below, which seems to show incompatibility with the package and machines with ARM based processors. The error message when using version=2.0 simulation.

> OSError: dlopen(/Users/thomaschen/WNTR/wntr/epanet/Darwin/libepanet.dylib, 0x0006): tried: '/Users/thomaschen/WNTR/wntr/epanet/Darwin/libepanet.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/thomaschen/WNTR/wntr/epanet/Darwin/libepanet.dylib' (no such file), '/Users/thomaschen/WNTR/wntr/epanet/Darwin/libepanet.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

And the message below for version=2.2 simulation

> OSError: dlopen(/Users/thomaschen/WNTR/wntr/epanet/Darwin/libepanet22_win32.dylib, 0x0006): tried: '/Users/thomaschen/WNTR/wntr/epanet/Darwin/libepanet22_win32.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/thomaschen/WNTR/wntr/epanet/Darwin/libepanet22_win32.dylib' (no such file), '/Users/thomaschen/WNTR/wntr/epanet/Darwin/libepanet22_win32.dylib' (no such file)

Was wondering if there is a version of this package where this is resolved?

**Comment by dbhart** [comment]
There is an issue with ARM M1 processors at this time, because we do not have a build machine. You will need to build the EPANET shared library from the EPANET source code first (github.com:OpenWaterAnalytics/EPANET), and place it in the correct location (replace the *darwin*.so file). The other binaries, for WNTR itself, you can build using pip/setup.py as described in the WNTR documentation.

I hope that M1-native builds become easier in the future, but at the moment ARM chipsets are not as easy to get pre-built binaries for.

Hope this helps, and interested in hearing how building EPANET on M1 goes
