### ISSUE TITLE
WNTR simulator issue

### ISSUE THREAD

**Issue by joardima** [USEPA/WNTR#329]
I'm using Python 3.9 and WNTR 0.3.1

I run a script using Epanet simulator, SIM = wntr.sim.EpanetSimulator(WN), and it run without errors.

If I change to WNTR simulator, SIM = wntr.sim.WNTRSimulator(WN), the following error appears:

  _File "C:\Users\jdi004\Anaconda3\envs\Thesis\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "d:\onedrive\ihe_hi\015. thesis\github_repositories\msc-thesis\wntr_main.py", line 86, in <module>
    WNTR_LSER = WNTR_Leak_Sim_EPANET(

  File "D:\OneDrive\IHE_HI\015. Thesis\Github_repositories\Msc-Thesis\WNTR_Leak_Sim_EPANET.py", line 126, in WNTR_Leak_Sim_EPANET
    RESULTS = SIM.run_sim()

  File "C:\Users\jdi004\Anaconda3\envs\Thesis\lib\site-packages\wntr\sim\core.py", line 950, in run_sim
    elif self._report_timestep.upper() == 'ALL':

AttributeError: 'numpy.float64' object has no attribute 'upper'_

What could be a solution for it?

Thanks in advance.

**Comment by kaklise** [comment]
Thanks for pointing this out.  `wn.options.time.report_timestep` can be an int, float, or "ALL".  numpy.float and numpy.int should also be allowed.  The issue is that WNTR incorrectly checked type and assumed that `report_timestep` was a string and then tried to apply `upper`.  I'll update the code to fix this issue.  In the meantime, just be sure to use a float or int (instead of a numpy.float) to define the `wn.options.time.report_timestep`.
