### ISSUE TITLE
PUMP OVERFLOW AND HOW TO PICK THE PRESSURE ND DEMAND ON NODES WHEN PARTIAL RESULTS IS RETURNED DUE TO NON-CONVERGENCE

### ISSUE THREAD

**Issue by uthmankareem** [USEPA/WNTR#357]
Hello,

I am running an extended "PDD" simulation using wntr. Sometimes, I get warnings on pump overflow. I do not know what causes this and how I can address it. Is it anything I need to worry about. Otherwise, I will ignore it.

The second question is that I under stand I can access the pressure in the nodes by picking a time index. 
for example, I use this code below to access where pressure is greater than required pressure. However, I get a key error 0 when the simulation does not converge. May be in a situation where partial results is returned. How do I manage this and still be able to pick access these values? In fact, the error comes up on the third line of code below.
"pressure_above_threshold = wntr.metrics.query(pres, np.greater,threshold)
pressure_above_thresholdT = pressure_above_threshold.T  
pressure_below_threshold_lst = pressure_above_thresholdT.index[pressure_above_thresholdT[0] == False].tolist()"

Thank you.

**Environment**
[Optional] Provide information on your computing environment.
 - Operating system: OS 10
 - Python version: 3.7
 - WNTR version:

**Comment by kaklise** [comment]
EPANET will warn the user if pumps try to operate outside the range of its pump curve.  The pumps will not overflow (tanks can overflow), the pump will shut down (due to insufficient head) or operate beyond the max flowrate.

For the second question, I suggest checking to make sure the simulation completed the first timestep (timestep 0).  Looks like pressure_above_thresholdT does not include index 0.  This can occur when the simulation does not converge.
