### ISSUE TITLE
Smaller and variable step-size for solver

### ISSUE THREAD

**Issue by Stormyend** [USEPA/WNTR#362]
Hi,
first of all thanks a lot for the amazing work done for WNTR!

I want to simulate hydraulic simulations in python, but on a smaller scale than in WNTR with more dynamic systems.
Since the basic equations are the same I am able to do that quite well, however there are limitations due to the step-size.
What are the issues with being able to use step-sizes smaller than 1s?
And would it even be possible to integrate a variable step-size solver?

Thanks!

**Comment by dbhart** [comment]
Hi, and thanks for the question. There are researchers using WNTR for build-sized plumbing, so you are correct that the equations will work for small systems. We are in the process of finalizing the interactive solver code for importing into the main branch, and it allows for iteration of the EpanetSolver over single steps, and it is possible to change the hydraulic step dynamically during that process. However, the 1-second solver limitation for the EpanetSolver is a limitation in EPANET itself.

**Comment by Stormyend** [comment]
Hi @kbonney , thanks for your response! I understand that the requirement for the timestep is to be >=1, however I was wondering where this limitation comes from, as it is no limitation given by the solver or the equations, but given by the WNTR framework. When I rewrite the modulo-statements to work with floats/timesteps < 1 and bypass the if-statements, the simulation results still seem to be correct.
However I was wondering what the reason for the limitation is in the first place.
I hope my question is clear, thank you very much in advance!

**Comment by michaelbynum** [comment]
@Stormyend - Are you using the EPANET simulator or the WNTR simulator?

**Comment by michaelbynum** [comment]
This is not a "real" limitation. You are absolutely right. I think we just never considered going less than 1 second. I think there is some logic in there that relies on the time step being an integer (which is why we make sure it is an integer), but that is just an implementation detail. It could certainly be updated.

**Comment by ucchejbb** [comment]
@Stormyend for reference EPANET-MSX now allows microsecond timesteps but as ints (which limits the total duration of a simulation to about 595 hours for extended period simulations). The one consideration when using a float is precision, so will 0.1 or 0.01 timesteps always yield 10 or 100 intervals per second because of machine precision? An alternative approach would be to include a subsecond loop with another range of ints to avoid that possible edge case.

**Comment by Stormyend** [comment]
Thank you both for the comments! I will keep the float precision problem in mind when implementing it! :)
