### ISSUE TITLE
Choose location for temp files en*****

### ISSUE THREAD

**Issue by bernardo-suez** [USEPA/WNTR#367]
**Summary**
Is there a way of setting the location where the temp files en***** (e.g., enXifTH) will be saved? I'm running about two hundred simulations in parallel of a really model on a VM with very limited permanent storage (where WNTR is installed) but very high temp storage.

**Environment**
 - Operating system: Ubuntu 22.04
 - Python version: 3.9
 - WNTR version: 0.41

**Comment by dbhart** [comment]
Hi @bernardo-suez 
The location of the en****** file is based on the EPANET binary - unfortunately, it isn't easy to change where it puts things, since it's embedded in the C code. 

However, I do have a workaround. It will put the en***** temp file in the directory you are in, in the interpreter. So,

`import os`
`os.chdir(os.path.join(['path','to','my','temp','dir']))`
`sim.run_sim(file_prefix='prefix')`
`os.chdir(os.path.join(['path','to','a','different','dir']))`
`...`

This should do what you are looking for. If this doesn't work, please let me know (I got it to work this way on my Mac, but I don't have an Ubuntu machine to verify on).
