### ISSUE TITLE
WNTR not plotting the network graph

### ISSUE THREAD

**Issue by Mattii1994** [USEPA/WNTR#64]
Hello. I start work with WNTR. It will help me in my master thesis. I have a problem with plotting in Pycharm IDE. When I used a getting_started script in Pycharm I don't got any graph. I have every required python package. However When I used Spyder in terminal i got a small picture of graph.

What's the problem. Pycharm doesn't support WNTR or I have problem with python package?
(I use Python 3.6.7 in Ubuntu 18.04)

**Comment by kaklise** [comment]
The graphics did not show up because we did not include “plt.show()” at the end of the script.  This statement is automatically included in Spyder but not in PyCharm.  I believe we omitted this line of code so that the examples also run from the command line.  When using PyCharm, you can add "plt.show()" at the end of your script. We'll look into options that make this work for IDE and command line.

**Comment by Mattii1994** [comment]
Thx for a help :)
