### ISSUE TITLE
is there a way to efficiently extract base demand from junction?

### ISSUE THREAD

**Issue by tyjchen** [USEPA/WNTR#80]
the question is pretty self explanatory, i tried digging around the junction object directories and couldn't find anything. any tips would be appreciated!

**Comment by kaklise** [comment]
Since junctions can have multiple demands, we don't have a simple 'base_demand' attribute on junctions.  You can use `wntr.metrics.expected_demand(wn)` to compute demands.  This function does not require a hydraulic simulation, it loops through the multiple demands on each junction and computes the total demand at each time step using the base value, pattern, and demand multiplier.

**Comment by tyjchen** [comment]
thank you!
