### ISSUE TITLE
[EpanetSimulator] result_types option does not change the results object

### ISSUE THREAD

**Issue by pshassett** [USEPA/WNTR#96]
A few issues related to using the result_types option of EpanetSimulator:

1. The documentation on [wntr.sim.epanet.EpanetSimulator](https://wntr.readthedocs.io/en/latest/apidoc/wntr.sim.epanet.html#wntr.sim.epanet.EpanetSimulator) defines that result_types should be a dict, however documentation on [wntr.epanet.io.BinFile](https://wntr.readthedocs.io/en/latest/apidoc/wntr.epanet.io.html#wntr.epanet.io.BinFile), where result_types is passed, defines _'results_type'_ as a list. Possible typo(s)?
2. When the user-specified result_types is passed from wntr.sim.epanet.EpanetSimulator as a parameter for wntr.epanet.io.BinFile:
`self.reader = wntr.epanet.io.BinFile(result_types=result_types)`,  result_types is saved to wntr.epanet.io.BinFile attribute _self_.items.  _self_.items however is only used in the custom handler methods.
When wntr.sim.epanet.EpanetSimulator.run_sim() reaches its end and calls:
`return self.reader.read(outfile)`, wntr.epanet.io.BinFile.read() is executed with  kwarg `custom_handlers = False`, resulting in the items specified by result_types are never being used.  

3. There doesn't seem to be any simple way to use the custom handlers without writing a custom child class of wntr.epanet.io.BinFile?  

Maybe I am misunderstanding the intended use of result_types from the API documentation, in which case perhaps the related docs need to be updated to clarify.

**Comment by dbhart** [comment]
You are correct on all counts. Originally, the result_types was a dict and changed to a list. The simulator by default gets all results unless a custom subclass is used. Reading all data instead of specifying which results to keep resulted in a huge performance improvement, so we kept it that way and forgot to update the docs.

- Dave Hart, Sent from my iPhone

On May 29, 2019, at 3:23 PM, pshassett <notifications@github.com<mailto:notifications@github.com>> wrote:


A few issues related to using the result_types option of EpanetSimulator:

  1.  The documentation on wntr.sim.epanet.EpanetSimulator<https://wntr.readthedocs.io/en/latest/apidoc/wntr.sim.epanet.html#wntr.sim.epanet.EpanetSimulator> defines that result_types should be a dict, however documentation on wntr.epanet.io.BinFile<https://wntr.readthedocs.io/en/latest/apidoc/wntr.epanet.io.html#wntr.epanet.io.BinFile>, where result_types is passed, defines 'results_type' as a list. Possible typo(s)?

  2.  When the user-specified result_types is passed from wntr.sim.epanet.EpanetSimulator as a parameter for wntr.epanet.io.BinFile:
self.reader = wntr.epanet.io.BinFile(result_types=result_types), result_types is saved to wntr.epanet.io.BinFile attribute self.items. self.items however is only used in the custom handler methods.
When wntr.sim.epanet.EpanetSimulator.run_sim() reaches its end and calls:
return self.reader.read(outfile), wntr.epanet.io.BinFile.read() is executed with kwarg custom_handlers = False, resulting in the items specified by result_types are never being used.

  3.  There doesn't seem to be any simple way to use the custom handlers without writing a custom child class of wntr.epanet.io.BinFile?

Maybe I am misunderstanding the intended use of result_types from the API documentation, in which case perhaps the related docs need to be updated to clarify.

**Comment by pshassett** [comment]
Hi David, Thanks for clarifying.  So similarly, the `wn.options.results.results_obj` attribute is never used in either the WNTR or EPANET simulators?

**Comment by kaklise** [comment]
Documentation updated in #99
